theme: jekyll-theme-time-machine
title: Mikado Testbuilders Kata

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include: 
  - docs
  - LICENSE
  - LICENSE.txt
  - docs/1_Introduction.md
  - docs/2_Easy_Fix_Difficult_Test.md
  - docs/3_Building_Test_Data.md
  - docs/4_Mikado_Method_to_the_Rescue.md
  - docs/5_Conclusion.md
  - docs/Animation_Guide.md
  - docs/references/References.md
  - docs/references/Test_Data_Builders.md
  - docs/references/The_Mikado_Method.md